version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "GratitudeTodayStack"
s3_bucket = "gratitudetoday"
s3_prefix = ""
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
